version: '3.8'

services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./frontend/build:/usr/share/nginx/html
    depends_on:
      - user-service
      - property-service

  user-service:
    build: ./user-service
    ports:
      - "8000:8000"
    environment:
      - DEBUG=True
      - ALLOWED_HOSTS=localhost,user-service

  property-service:
    build: ./property-service
    ports:
      - "8001:8000"
    environment:
      - DEBUG=True
      - ALLOWED_HOSTS=localhost,property-service