# Generated by Django 5.2.1 on 2025-06-23 01:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('user_app', '0001_initial'), ('user_app', '0002_profile_role_alter_profile_phone_alter_profile_user'), ('user_app', '0003_remove_profile_id_alter_profile_role_and_more')]

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('phone', models.CharField(blank=True, max_length=15)),
                ('address', models.TextField(blank=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('role', models.CharField(choices=[('admin', 'Administrator'), ('operator', 'System Operator'), ('agent', 'Support Agent'), ('buyer', 'Buyer'), ('seller', 'Seller')], default='buyer', max_length=20)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user',), name='unique_user_profile')],
            },
        ),
    ]
